# Generated by Django 4.1 on 2022-09-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_books_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='qty',
            new_name='Qty',
        ),
    ]
