# Generated by Django 4.1 on 2022-09-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_books_name_rename_price_books_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Qty',
            new_name='qty',
        ),
    ]
